services:
  # 1) Zep Public Web Service (built from your Dockerfile)
  - name: zep
    type: web
    image:
      url: db402/zep-custom:latest
    autoDeploy: false
    build:
      dockerfilePath: Dockerfile.ce
    healthCheckPath: /healthz
    envVars:
      - key: ZEP_CONFIG_FILE
        value: zep.yaml
      - key: POSTGRES_HOST
        fromDatabase:
          name: zep-postgres
          property: host
      - key: POSTGRES_DATABASE
        fromDatabase:
          name: zep-postgres
          property: databaseName
      - key: POSTGRES_USER
        fromDatabase:
          name: zep-postgres
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: zep-postgres
          property: password
      - key: POSTGRES_PORT
        value: "5432"
      - key: ZEP_API_SECRET
        sync: false
        value: "blahblahblah"
      - key: ZEP_OPENAI_API_KEY
        sync: false
        value: "sk-XXXX"
      - key: ZEP_SERVER_WEB_ENABLED
        value: "true"
      # Internal endpoints for Graphiti and Neo4j
      - key: GRAPHITI_HOST
        value: graphiti
      - key: GRAPHITI_PORT
        value: "8003"
      - key: NEO4J_HOST
        value: neo4j
      - key: NEO4J_PORT
        value: "7687"

  # 2) Graphiti Private Service
  - name: graphiti
    type: pserv
    env: image
    autoDeploy: false
    image:
      url: zepai/graphiti:0.3
    ports:
      - 8003
    envVars:
      - key: OPENAI_API_KEY
        sync: false
        value: "sk-XXXX"
      - key: MODEL_NAME
        value: "gpt-4o-mini"
      - key: NEO4J_HOST
        value: neo4j
      - key: NEO4J_PORT
        value: "7687"

  # 3) Neo4j Private Service
  - name: neo4j
    type: pserv
    env: image
    autoDeploy: false
    image:
      url: neo4j:5.22.0
    envVars:
      - key: NEO4J_AUTH
        sync: false
        value: "neo4j/zepzepzep"
    ports:
      - 7474
      - 7687

databases:
  # 4) Managed PostgreSQL Database
  - name: zep-postgres
    databaseName: zep
    postgresMajorVersion: 15
    ipAllowList: []
