# render.yaml
services:
  # 1) Zep Public Web Service
  - name: zep
    type: web
    env: docker
    image:
      url: db402/zep-custom:latest
    plan: free             # Adjust plan as needed
    autoDeploy: false
    healthCheckPath: /healthz
    envVars:
      - key: POSTGRES_HOST
        sync: false
      - key: POSTGRES_DATABASE
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_PORT
        value: "5432"

      # Zep application config
      - key: ZEP_API_SECRET
        sync: false
      - key: ZEP_OPENAI_API_KEY
        sync: false
      - key: ZEP_SERVER_WEB_ENABLED
        sync: false

      # Internal service references
      - key: GRAPHITI_HOST
        sync: false
      - key: GRAPHITI_PORT
        value: 8003
      - key: NEO4J_HOST
        sync: false
      - key: NEO4J_PORT
        value: 7687

  # 2) Graphiti Private Service
  - name: graphiti
    type: pserv
    env: docker
    image:
      url: zepai/graphiti:0.3
    plan: free
    autoDeploy: false
    # Remove "ports" field; the container’s internal port (8003) is used for internal communication.
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: MODEL_NAME
        value: "gpt-4o-mini"
      - key: NEO4J_HOST
        sync: false
      - key: NEO4J_PORT
        value: 7687

  # 3) Neo4j Private Service
  - name: neo4j
    type: pserv
    env: docker
    image:
      url: neo4j:5.22.0
    plan: free
    autoDeploy: false
    # Remove "ports" field; internal connectivity will use the container’s native ports.
    envVars:
      - key: NEO4J_AUTH
        sync: false

databases:
  # 4) Managed PostgreSQL Database
  - name: zep-postgres
    databaseName: zep
    postgresMajorVersion: 15
    ipAllowList: []
