# render.yaml
services:
  # 1) Zep Public Web Service
  - name: zep
    type: web
    env: docker
    image:
      url: db402/zep-custom:latest
    plan: free              # or "starter"/"standard", etc.
    autoDeploy: false
    healthCheckPath: /healthz
    envVars:
      # These can be replaced by direct references or removed if you supply them in the dashboard
      - key: POSTGRES_HOST
        value: ""
      - key: POSTGRES_DATABASE
        value: ""
      - key: POSTGRES_USER
        value: ""
      - key: POSTGRES_PASSWORD
        value: ""
      - key: POSTGRES_PORT
        value: "5432"

      # Example placeholders for any app config
      - key: ZEP_API_SECRET
        value: ""
      - key: ZEP_OPENAI_API_KEY
        value: ""
      - key: ZEP_SERVER_WEB_ENABLED
        value: "true"

      # Graphiti / Neo4j internal references (override if needed)
      - key: GRAPHITI_HOST
        value: "graphiti"
      - key: GRAPHITI_PORT
        value: "8003"
      - key: NEO4J_HOST
        value: "neo4j"
      - key: NEO4J_PORT
        value: "7687"

  # 2) Graphiti Private Service
  - name: graphiti
    type: pserv
    env: docker
    image:
      url: zepai/graphiti:0.3
    plan: free
    autoDeploy: false
    ports:
      - containerPort: 8003
    envVars:
      - key: OPENAI_API_KEY
        value: ""
      - key: MODEL_NAME
        value: "gpt-4o-mini"
      - key: NEO4J_HOST
        value: "neo4j"
      - key: NEO4J_PORT
        value: "7687"

  # 3) Neo4j Private Service
  - name: neo4j
    type: pserv
    env: docker
    image:
      url: neo4j:5.22.0
    plan: free
    autoDeploy: false
    ports:
      - containerPort: 7474
      - containerPort: 7687
    envVars:
      - key: NEO4J_AUTH
        value: "neo4j/zepzepzep"

databases:
  # 4) Managed PostgreSQL Database
  - name: zep-postgres
    databaseName: zep
    postgresMajorVersion: 15
    ipAllowList: []
