services:
  - type: web
    name: zep
    autoDeploy: false
    env: image
    image:
      url: db402/zep-custom:latest  # Changed to your custom Docker image URL
    healthCheckPath: /healthz
    envVars:
      # Disable web UI. WARNING: Do not enable this unless
      # you are running Zep on a private network.
      - key: ZEP_SERVER_WEB_ENABLED
        value: "false"
      - key: PORT
        value: 8000
      - key: ZEP_STORE_POSTGRES_DSN
        fromDatabase:
          name: zep-postgres
          property: connectionString
      - key: ZEP_NLP_SERVER_HOSTPORT
        fromService:
          name: zep-nlp
          type: pserv
          property: hostport
      - key: ZEP_OPENAI_API_KEY
        sync: false
  - type: pserv
    name: zep-nlp
    autoDeploy: false
    env: image
    image:
      url: ghcr.io/getzep/zep-nlp-server:latest
