services:
  - type: web
    name: zep6-dy76
    autoDeploy: false
    env: image
    image:
      url: db402/zep-custom:latest
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: "8000"
      - key: ZEP_STORE_POSTGRES_DSN
        fromDatabase:
          name: zep-postgres-dy76
          property: connectionString
      - key: GRAPHITI_HOSTPORT
        fromService:
          name: graphiti-dy76
          type: pserv
          property: hostport
      - key: NEO4J_HOSTPORT
        fromService:
          name: neo4j-dy76
          type: pserv
          property: hostport
      - key: ZEP_API_SECRET
        sync: false
      - key: ZEP_OPENAI_API_KEY
        sync: false
      - key: ZEP_SERVER_WEB_ENABLED
        sync: false


  - type: pserv
    name: graphiti-dy76
    autoDeploy: false
    env: image
    image:
      url: zepai/graphiti:0.3

  - type: pserv
    name: neo4j
    autoDeploy: false
    env: image
    image:
      url: neo4j:5.22.0

databases:
  - name: zep-postgres-dy76
    databaseName: zep
    postgresMajorVersion: 16
    ipAllowList: []
