services:
  - type: web
    name: zep
    autoDeploy: false
    env: image
    image:
      url: db402/zep-custom:latest
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: "8000"
      - key: ZEP_STORE_POSTGRES_DSN
        fromDatabase:
          name: zep-postgres
          property: connectionString
      - key: GRAPHITI_HOSTPORT
        fromService:
          name: graphiti
          type: pserv
          property: hostport
      - key: NEO4J_HOSTPORT
        fromService:
          name: neo4j
          type: pserv
          property: hostport
      - key: ZEP_API_SECRET
        sync: false
      - key: ZEP_OPENAI_API_KEY
        sync: false
      - key: ZEP_SERVER_WEB_ENABLED
        sync: false


  - type: pserv
    name: graphiti
    autoDeploy: false
    env: image
    image:
      url: zepai/graphiti:0.3

  - type: pserv
    name: neo4j
    autoDeploy: false
    env: image
    image:
      url: neo4j:5.22.0
    disks:
      - name: neo4j_data
        mountPath: /data

databases:
  - name: zep-postgres
    databaseName: zep
    postgresMajorVersion: 16
    ipAllowList: []
